#debug: 1                 # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM1
frame_id: gps2

uart1:
  baudrate: 460800
uart2:
  baudrate: 460800
config_on_startup: false

rate: 10                    # in Hz
nav_rate: 10                  # [# of measurement cycles], recommended 1 Hz, may

dynamic_model: automotive    # automotive mode

dgnss_mode: 3

tmode3: 0

gnss:
  gps: true
  glonass: true
  beidou: false
  qzss: false
  galileo: false
  imes: false
  sbas: false

# Enable u-blox message publishers
publish:
  all: false
  nav:
    all: false
    relposned: true
    heading: true
    posllh: false
    posecef: false
